# Generated by Django 5.1.1 on 2024-09-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblood', '0008_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donar_signup_info',
        ),
        migrations.AlterField(
            model_name='donar_donate_info',
            name='img',
            field=models.URLField(),
        ),
    ]
